// Redux constants here, follow this format

export const GET_ERRORS = 'GET_ERRORS';

// Authentication types
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const GUEST_USER = 'GUEST_USER';
export const AUTH_ERROR = 'AUTHENTICATION_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REG_SUCCESS = 'REGISTER_SUCCESS';
export const REG_FAILURE = 'REGISTER_FAILURE';

// Load all types of stocks with their code and company name (no other properties)
export const COMPANIES_LOADING = 'COMPANIES_LOADING';
export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';
export const COMPANIES_FAILURE = 'COMPANIES_FAILURE';

// Load specific stock detail (inc. prices [low, high, open, close])
export const STOCK_LOADING = 'STOCK_LOADING';
export const STOCK_SUCCESS = 'STOCK_SUCCESS';
export const STOCK_FAILURE = 'STOCK_FAILURE';

// Load analytics
export const TOP_GAINERS_LOADING = 'TOP_GAINERS_LOADING';
export const TOP_GAINERS_SUCCESS = 'TOP_GAINERS_SUCCESS';
export const TOP_GAINERS_FAILURE = 'TOP_GAINERS_FAILURE';

export const TOP_DECLINES_LOADING = 'TOP_DECLINES_LOADING';
export const TOP_DECLINES_SUCCESS = 'TOP_DECLINES_SUCCESS';
export const TOP_DECLINES_FAILURE = 'TOP_DECLINES_FAILURE';

export const TOP_COMPANIES_LOADING = 'TOP_COMPANIES_LOADING';
export const TOP_COMPANIES_SUCCESS = 'TOP_COMPANIES_SUCCESS';
export const TOP_COMPANIES_FAILURE = 'TOP_COMPANIES_FAILURE';

export const INDUSTRY_INDICES_LOADING = 'INDUSTRY_INDICES_LOADING';
export const INDUSTRY_INDICES_SUCCESS = 'INDUSTRY_INDICES_SUCCESS';
export const INDUSTRY_INDICES_FAILURE = 'INDUSTRY_INDICES_FAILURE';

// Portfolio loading
export const PORTFOLIOS_LOADING = 'PORTFOLIOS_LOADING';
export const PORTFOLIOS_SUCCESS = 'PORTFOLIOS_SUCCESS';
export const PORTFOLIOS_FAILURE = 'PORTFOLIOS_FAILURE';

// Portfolio performance
export const PORTFOLIOS_PERFORMANCE_LOADING = 'PORTFOLIOS_PERFORMANCE_LOADING';
export const PORTFOLIOS_PERFORMANCE_SUCCESS = 'PORTFOLIOS_PERFORMANCE_SUCCESS';
export const PORTFOLIOS_PERFORMANCE_FAILURE = 'PORTFOLIOS_PERFORMANCE_FAILURE';

export const PORTFOLIO_HISTORICAL_PERFORMANCE_LOADING =
  'PORTFOLIO_HISTORICAL_PERFORMANCE_LOADING';
export const PORTFOLIO_HISTORICAL_PERFORMANCE_SUCCESS =
  'PORTFOLIO_HISTORICAL_PERFORMANCE_SUCCESS';
export const PORTFOLIO_HISTORICAL_PERFORMANCE_FAILURE =
  'PORTFOLIO_HISTORICAL_PERFORMANCE_FAILURE';

export const HOLDING_GROUP_HISTORICAL_LOADING =
  'HOLDING_GROUP_HISTORICAL_LOADING';
export const HOLDING_GROUP_HISTORICAL_SUCCESS =
  'HOLDING_GROUP_HISTORICAL_SUCCESS';
export const HOLDING_GROUP_HISTORICAL_FAILURE =
  ' HOLDING_GROUP_HISTORICAL_FAILURE';

//Add or delete porfolios
export const ADD_PORTFOLIO_LOADING = 'ADD_PORTFOLIO_LOADING';
export const ADD_PORTFOLIO_SUCCESS = 'ADD_PORTFOLIO_SUCCESS';
export const ADD_PORTFOLIO_FAILURE = 'ADD_PORTFOLIO_FAILURE';

export const DELETE_PORTFOLIO_LOADING = 'DELETE_PORTFOLIO_LOADING';
export const DELETE_PORTFOLIO_SUCCESS = 'DELETE_PORTFOLIO_SUCCESS';
export const DELETE_PORTFOLIO_FAILURE = 'DELETE_PORTFOLIO_FAILURE';

// Add or delete holdings
export const ADD_HOLDING_LOADING = 'ADD_HOLDING_LOADING ';
export const ADD_HOLDING = 'ADD_HOLDING';
export const DELETE_HOLDING_LOADING = 'DELETE_HOLDING_LOADING';
export const DELETE_HOLDING = 'DELETE_HOLDING';

//Game Types
export const GAME_REG_SUCCESS = 'GAME_REGISTER_SUCCESS';
export const GAME_REGISTER_FAILURE = 'GAME_REGISTER_FAILURE';

//FOUND USER BASE ON TOKEN
export const USER_FOUND = 'USER_FOUND';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';

//Game Portfolio
// Portfolio loading
export const GAME_PORTFOLIOS_LOADING = 'GAME_PORTFOLIOS_LOADING';
export const GAME_PORTFOLIOS_SUCCESS = 'GAME_PORTFOLIOS_SUCCESS';
export const GAME_PORTFOLIOS_FAILURE = 'GAME_PORTFOLIOS_FAILURE';

//Add or delete porfolios
export const GAME_ADD_PORTFOLIO_LOADING = 'GAME_ADD_PORTFOLIO_LOADING';
export const GAME_ADD_PORTFOLIO_SUCCESS = 'GAME_ADD_PORTFOLIO_SUCCESS';
export const GAME_ADD_PORTFOLIO_FAILURE = 'GAME_ADD_PORTFOLIO_FAILURE';

export const GAME_DELETE_PORTFOLIO_LOADING = 'GAME_DELETE_PORTFOLIO_LOADING';
export const GAME_DELETE_PORTFOLIO_SUCCESS = 'GAME_DELETE_PORTFOLIO_SUCCESS';
export const GAME_DELETE_PORTFOLIO_FAILURE = 'GAME_DELETE_PORTFOLIO_FAILURE';

// Add or delete holdings
export const GAME_ADD_HOLDING_LOADING = 'GAME_ADD_HOLDING_LOADING ';
export const GAME_ADD_HOLDING = 'GAME_ADD_HOLDING';
export const GAME_DELETE_HOLDING_LOADING = 'GAME_DELETE_HOLDING_LOADING';
export const GAME_DELETE_HOLDING = 'GAME_DELETE_HOLDING';
export const GAME_SELL_HOLDING_LOADING = 'GAME_SELL_HOLDING_LOADING';
export const GAME_SELL_HOLDING = 'GAME_SELL_HOLDING';
export const GAME_RESET = 'GAME_RESET';

// Edit portfolio
export const EDIT_PORTFOLIO_LOADING = 'EDIT_PORTFOLIO_LOADING';
export const EDIT_PORTFOLIO_SUCCESS = 'EDIT_PORTFOLIO_SUCCESS';
export const EDIT_PORTFOLIO_FAILURE = 'EDIT_PORTFOLIO_FAILURE';

// Stock Screener
export const STOCK_SCREENER_LOADING = 'STOCK_SCREENER_LOADING';
export const STOCK_SCREENER_SUCCESS = 'STOCK_SCREENER_SUCCESS';
export const STOCK_SCREENER_FAILURE = 'STOCK_SCREENER_FAILURE';



