
class types():
    USER_LOADING = "USER_LOADING"
    USER_LOADED = "USER_LOADED"
    GUEST_USER = "GUEST_USER"
    AUTH_ERROR = "AUTHENTICATION_ERROR"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    REG_SUCCESS = "REGISTER_SUCCESS"
    REG_FAILURE = "REGISTER_FAILURE"
    GAME_REG_SUCCESS = "GAME_REGISTER_SUCCESS"
    GAME_REGISTER_FAILURE= "GAME_REGISTER_FAILURE"   
    USER_FOUND= "USER_FOUND"
    USER_NOT_FOUND= "USER_NOT_FOUND"
    def __init__(self):
        pass
        